name: Tests

on: [push, pull_request]

jobs:
    checks:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Ensure fresh npm version
              run: npm install -g npm@latest

            - name: Build Env Information
              run: |
                  node -v
                  npm -v

            - name: Install dependencies
              run: npm ci

            - name: Type check
              run: npm run type-check

            - name: Lint check
              run: npm run lint-check

            - name: Format check
              run: npm run format-check

            - name: Test Vite Build
              run: npm run build
              env:
                  NODE_OPTIONS: "--max-old-space-size=8192"
